### ISSUE TITLE
Timer header and source files missing from 2.1.0 release

### ISSUE THREAD

**Issue by ajschwieterman** [robertgallup/arduino-BobaBlox#1]
When I upgraded my copy of this library from 2.0.1 to 2.1.0, I received this error after compiling my code.
```
/Users/aaronschwieterman/Documents/Arduino/libraries/BobaBlox/src/BobaBlox.h:36:10: fatal error: utility/Timer.h: No such file or directory
   36 | #include "utility/Timer.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1
```
After checking the library directory, these were the files that were installed.
<img width="256" alt="Screenshot 2022-12-03 at 22 54 46" src="https://user-images.githubusercontent.com/50152740/205473527-b058fd78-79c1-4558-8809-c5b7d18a9c0b.png">

**Comment by robertgallup** [comment]
Thanks for pointing this out! I'm not exactly sure what the problem is because the files are in the GitHub repository. However, I noticed a URL error in the library.properties file. I've fixed that, and bumped the version to 2.2.0. I don't know how long it will take to propagate to the IDE. If you want to use the timer before then, you can copy the files directly from GitHub. I'll keep checking to see when the are available from the Library Manager and post here when it happens (and, hopefully, close this issue :) )

**Comment by robertgallup** [comment]
BobaBlox is still showing 2.1.0 in the Arduino IDE. After some research, I remembered that I renamed the BobaBlox library repository some time ago while normalizing the names of my repositories. I think this broke the link to the Arduino library manager. So, I've just now renamed the BobaBlox repository back to its original name. Have to wait and see if that propagates to the IDE.

**Comment by robertgallup** [comment]
I've just confirmed that V2.2.0 includes the Timer files and compiles the timer example. It would be great if you could confirm on your side and let me know if this fixes your issue. Otherwise, I'll close this shortly as resolved. Thanks again for pointing the issue out!

**Comment by ajschwieterman** [comment]
I can confirm the Timer files compile with v2.2.0!  Thank you for updating the library so quickly!  Much appreciated!  😀

**Comment by robertgallup** [comment]
Great! Thanks for letting me know. :)
